---
driver:
  name: vagrant
  driver_config:
    network:
      - ["forwarded_port", {guest: 3389, host: 3389}]
  customize:
    memory: 6144

transport:
  name: winrm
  username: vagrant
  password: vagrant

provisioner:
  name: chef_zero
  always_update_cookbooks: true

verifier:
  name: inspec

platforms:
  - name: win2012r2

suites:
  - name: default
    run_list:
      # - recipe[windows-ca::ad-domain-controller]
      # - recipe[windows-ca::certificate-authority]
      - recipe[windows-ca::default]
    verifier:
      inspec_tests:
        - test/smoke/default
    attributes:
